now_escape/App.js, now_escape/Loading.js, now_escape/Main.js, now_escape/package-lock.json, now_escape/package.json
Splash 화면 생성하였습니다. 
초기 화면 App.js에 Loading.js와 Main.js를 추가하였고
Loading은 처음 10초간(임의로 설정) 보여지고
그 후 Main으로 넘어가도록 설정하였습니다.
css는 일단 js 내부에 두었습니다.
=> #4 Splash 화면 생성

now_escape/components/ListItemDetail/listItemDetail.js
https://runebook.dev/ko/docs/react_native/platform-specific-code  참고
1. styles 작성 할 때 style 별로 (text:{ ios/android} 혹은 platform 별로 (ios:{text, container}. android:{text, container}) 중에 고민했는데 style별로 하는게 중복을 줄일 것 같고 알아보기도 쉬울 것 같아 이 방식으로 정함. flex, color 등등 공통 부분은 style에 적고 그 밑에 ios/android 나누어진 부분에 fontsize, margin과 같은 플랫폼 별로 다른 것을 적음
2. #24 추가해야 함
3. Main에서는 #20 의 커밋 내용을 참고, props에 synopsis 만 추가하면 됨
=> list_item_detail

now_escape/package-lock.json, now_escape/package.json, now_escape/store/genreStore.ts, now_escape/store/rigionStore.ts, now_escape/yarn.lock
- zustand install
- genreList, setGenre
- settingGenre : 누른게 false라면? 원래 true였던 걸 false로 바꾸고, 누른 걸 true로 변경하는 로직
=> add genreStore (zustand)

now_escape/components/setting/Genre/genre.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/yarn.lock
- genreStore marge version으로 디버깅 필요
- typeScript type 정의를 신경쓰지 않고 일단 개발
- style의 prop에 따라 변화하는게 없더라도 prop을 적어야 함 -> style을 나누어서 작성?
=> add setting/genre

now_escape/components/ListItem/listItem.js, now_escape/package-lock.json, now_escape/package.json, now_escape/screens/Index/Index.tsx, now_escape/store/escapeListStore.ts, now_escape/yarn.lock
- escapeListStore ajax 추가
- listItem api 구조에 맞게 수정
To do
- 무한 스크롤 추가
- index page Search Image 추가
- style 수정
=> add IndexPage, escapeListStore

now_escape/app.json, now_escape/assets/iconSearchBlack.tsx, now_escape/declarations.d.ts, now_escape/metro.config.js, now_escape/screens/Index/Index.tsx, now_escape/store/escapeListStore.ts
- search svg 추가
To do
상단 두 레이블 간 간격 조정
Related to: #14
=> Fix: "index css 수정"

now_escape/components/setting/Rigion/rigion.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/store/rigionStore.ts, now_escape/yarn.lock
- rigionStore파일 추가
- 배열 복사(settingRigion) 수정 중
Ref: #11
=> Add: "rigionStore 추가"

now_escape/Main.js, now_escape/components/setting/Time/time.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/store/timeStore.ts, now_escape/yarn.lock
- add time spinner, timeStore
- expo 라이브러리 사용
- 추후 api 연결에 따른 Store 구조 수정 필요
- 디자인 논의 필요
=> add setting/time, timeStore

now_escape/components/Label/label.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/screens/Search/Search.tsx, now_escape/store/genreStore.ts, now_escape/store/searchStore.ts
- genreStore에 현재 genre, genreListName 추가, setting/genre에서 장르를 선택할 때 genre value 수정 함수 추가 적용
- search 기능 구현 필요 (필터)
- 페이지 디자인 적용 필요 (typescript 파일에서만 style 중 margin, width 등 실행 안되는 것 확인 해결 필요
- label 수정
=> add searchPage

now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Time/time.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/screens/Index/Index.tsx, now_escape/screens/Search/Search.tsx, now_escape/store/dateStore.ts, now_escape/store/timeStore.ts, now_escape/yarn.lock
- date Store. setting/date
- date. time Modal 추가
- Search Page 기능 추가
- Index Page 수정
To do
유진 : 적용 버튼 눌러서 나갈 때에만 바꾼 value 적용 - 모든 기능 완성 후 추가
다은 : Index, Search Page 디자인에 맞게 수정(ios/android version), Modal 클릭 시 뒤 화면 rgba(0 0 0, 0.55) 로 되게 수정
=> add dateStore

now_escape/assets/iconArrowBack.tsx, now_escape/assets/iconSearchPink.tsx, now_escape/globalStyles.ts, now_escape/screens/Search/Search.tsx, now_escape/yarn.lock
- 현재 디바이스의 해상도를 가져오는 파일 추가
- search 페이지 css 수정
=> Fix: "search 페이지 css 수정"

now_escape/components/Label/label.tsx, now_escape/screens/Search/Search.tsx
- Search css  수정
- Label 왼쪽 아이콘 추가/오른쪽 화살표 방향/active시 색깔 수정
To do
- Label 클릭시 연결 되는 setting 컴포넌트 열기
- css 적용 안되는 부분 해결
- (논의) 레이아웃 배치 flexbox 여부
Related to: #35
=> Fix "Search/Label 수정"

now_escape/components/Label/label.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/screens/Search/Search.tsx
- ios에 맞추어 오류 수정 및 구현
- 디자인에 맞추다보니 불가피하게 genreSetting과 label도 수정함
To do
- 버튼 press가 아닌 setting이 오픈 되었을 때 label 색이 바뀌도록 적용
- (논의) safe area 관련 어떻게 처리할지
=> Fix "Search page css"

now_escape/components/setting/Rigion/rigion.tsx, now_escape/store/rigionStore.ts
- rigionStore, setting/rigion 추가
- rigion 관련 로직 추가
To do
유진 : search, Index page 연결 후 확인, page 연결
다은 : rigion component 디자인 수정, (연결 후 확인 작업 끝난 후) search, index page, search result page 디자인 수정, rigion, date, time 눌렀을 때 modal이 켜지면 뒷 배경 까맣게 되게 수정
=> add rigionStore, setting/rigion

now_escape/components/Label/label.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Rigion/rigion.tsx, now_escape/globalStyles_aos.ts, now_escape/globalStyles_ios.ts, now_escape/screens/Search/Search.tsx
- globalStyles ios/aos 로 분리
- globalStyle 파일 Import 했던 파일들도 수정
- rigion css 수정
=> "Fix: setting/rigion css"

now_escape/components/Label/label.tsx, now_escape/package-lock.json, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/yarn.lock
- label props 수정
- searchResult css 수정
=> Fix: "searchResult css"

now_escape/components/setting/Rigion/rigion.tsx
- 해당 페이지 플랫폼별 수정 완료(안드는 확인 작업 필요)
=> Fix: "RigionSetting 플랫폼별 디자인"

now_escape/assets/iconSearchBlack.tsx, now_escape/assets/iconSearchPink.tsx, now_escape/components/Label/label.tsx, now_escape/screens/Index/Index.tsx
=> Fix: "index css"

now_escape/components/setting/Date/date.tsx
=> Fix: "setting/date css"

now_escape/components/setting/Time/time.tsx
- 플랫폼별 css 수정
To do
- Picker의 높이가 조절이 되지 않는 것 해결하기
=> Fix: "setting/time css"

now_escape/screens/RigionSetting/RigionSetting.tsx
=> Fix: "modal 창으로 수정"

now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx
- listitem 클릭시 뜨는 listitemDetail Modal 위치 수정
- listitemDetail 플랫폼별 수정
=> Fix: "listItemDetail 수정"

now_escape/components/Label/label.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Time/time.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/screens/Search/Search.tsx, now_escape/yarn.lock
- search에서 genre setting height 수정
- search -> rigion setting 디자인 확인
- setting/time, date open시 뒷 화면 까만색 되게 적용 :: react-native-modal 라이브러리 설치하여 사용함
(참고 : https://github.com/react-native-modal/react-native-modal)
=> Fix: "Search page 관련 to do"

now_escape/App.tsx
=> add onLayoutRootView

now_escape/components/ListItem/listItem.tsx, now_escape/screens/Index/Index.tsx, now_escape/store/escapeListStore.ts
=> check reponsedata

now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/screens/Index/Index.tsx, now_escape/store/escapeListStore.ts
=> add EscapeList axios

now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/SearchResult/SearchResult.tsx
- index의 escapeList 부분 / escapeListDetail의 설명 부분 / genre 각 스크롤 모두 수정
=> Fix: "scroll error"

now_escape/components/Label/label.tsx, now_escape/components/ListItem/listItem.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Rigion/rigion.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/screens/Index/Index.tsx, now_escape/screens/RigionSetting/RigionSetting.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/store/searchStore.ts, now_escape/yarn.lock
=> filter logic

now_escape/components/Label/label.tsx, now_escape/components/ListItem/listItem.tsx, now_escape/components/setting/Rigion/rigion.tsx, now_escape/screens/RigionSetting/RigionSetting.tsx, now_escape/store/escapeListStore.ts, now_escape/store/searchStore.ts
- useEffect dependency array X
- ? 원인 찾기
- region 필터는 즉각적으로 처리되게 수정
=> searchData props 수정

now_escape/assets/iconTriangleDown.tsx, now_escape/components/Label/label.tsx, now_escape/screens/RigionSetting/RigionSetting.tsx
- rigionSetting 화면 label padding값, svg 크기 수정
- rigionSetting 화면 label 가이드텍스트 추가
=> Fix: "label icon/text"

now_escape/components/ListItem/listItem.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Time/time.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/store/genreStore.ts
- date 잘못 표기되는 것 수정
- 장르 바뀌는 것 확인
- 지역 바뀌는 것 확인
- searchResult page에서 Index Page re-rendering 때문에 제대로 된 값을 받아오지 못함 . 단순한 로직 문제인지 고민
=> post logic

now_escape/components/Label/label.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/screens/Search/Search.tsx
- textinput 위치 조정 및 가이드 텍스트(place holder) 추가
- 장르/지역 label text, svg 위치 조정
- 키보드 외부 혹은 다른 label 클릭 시 키보드 dismiss
- 검색 svg 및 키보드에 return 버튼 searchResult로 연결
- dateInput 과거 x
- genre modal sf/19금 텍스트 높이 맞도록 수정
=> Fix: "search css"

now_escape/assets/iconArrowBack.tsx, now_escape/assets/iconLocation.tsx, now_escape/components/Button/button.js, now_escape/components/Label/label.tsx, now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Rigion/rigion.tsx, now_escape/globalStyles_aos.ts, now_escape/screens/Index/Index.tsx, now_escape/screens/RigionSetting/RigionSetting.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx
- banner 스크롤 해결
- android 화면 수정사항
=> Fix: "android css"

now_escape/components/Label/label.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Time/time.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/RigionSetting/RigionSetting.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx
- time/date modal 디자인 오류
- searchResult 화면 지역/장르 label 순서
- safeArea도 white로 수정
=> Fix: "디자인 수정 사항"

now_escape/components/Button/button.js, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Time/time.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/yarn.lock
- date/time modal 수정 (modal library 추가 - https://www.npmjs.com/package/react-native-modal-datetime-picker/v/7.6.1)
- genre top margin 수정
- listItem column 수정
=> Fix: "android date/time css"

now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Date/date.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Rigion/rigion.tsx, now_escape/components/setting/Time/time.tsx, now_escape/store/escapeListStore.ts
=> add android date

now_escape/components/setting/Date/dateSetting.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/store/searchStore.ts
- search 화면 들어가면 setting 초기화 되는 로직 추가
=> add SearchLogic

now_escape/components/ListItem/listItem.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx
- 밑으로 당기면 새로고침
- Index로 돌아가면 setting 초기화
=> flat List refresh

now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Date/dateSetting.tsx, now_escape/screens/SearchResult/SearchResult.tsx
=> Fix: "aos datePicker"

now_escape/App.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/store/regionStore.ts, now_escape/yarn.lock
- import 했을 때 오류 (방식의 문제? 혹은 ts의 문제? 혹은 ....)
=> add persist

now_escape/components/setting/Date/dateSetting.tsx
=> Fix: "maximum date"

now_escape/App.tsx, now_escape/screens/RegionSetting/RegionSetting.tsx, now_escape/store/regionStore.ts
- Region Setting Page 계속 등장 버그 수정
=> add AsyncStorage

now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/screens/Index/Index.tsx
- 테마의 남은 시간이 3줄일 때 detail에서 시놉시스 칸을 줄이도록 하기
- index의 region 라벨의 text가 6자 이상일 때 말줄임표로 보이도록 수정
=> Fix: "label / listItemDetail"

now_escape/app.json, now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/components/setting/Date/dateSetting.tsx, now_escape/components/setting/Genre/genre.tsx, now_escape/components/setting/Region/region.tsx, now_escape/components/setting/Time/time.tsx, now_escape/screens/Index/Index.tsx, now_escape/screens/Search/Search.tsx, now_escape/screens/SearchResult/SearchResult.tsx, now_escape/store/escapeListStore.ts
- 방탈출 예약 시간 정렬
- 방탈출 리스트 초기화 로직 추가
=> 1.0.2 update

now_escape/app.json, now_escape/components/ListItem/listItem.tsx, now_escape/components/ListItemDetail/listItemDetail.tsx, now_escape/package-lock.json, now_escape/package.json, now_escape/yarn.lock
- text ticker 라이브러리 설치, 적용
- app 버전 미리 업데이트
- text ticker를 위한 text box width 설정 (android, ios 별 list, list detail 확인 필요)
=> add text ticker

now_escape/App.tsx
=> Fix: "SplashScreen"
